spring:
  datasource:
   driver-class-name: org.postgresql.Driver
   url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}${DB_OPTIONS}
   username: ${DB_USER_NAME}
   password: ${DB_PASSWORD}
   properties:
     charSet: UTF-8
   hikari:
     minimumIdle: 2
     maximumPoolSize: 10
     idleTimeout: 10000
     poolName: ProductionHikariCP
     maxLifetime: 7200000
     connectionTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
