name: Template CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: local_test_caseworker_db
          POSTGRES_USER: test_dev_user
          POSTGRES_PASSWORD: test_dev_password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
       # Server tests
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        working-directory: ./Server
        run: chmod +x ./gradlew

      - name: Build
        working-directory: ./Server
        run: ./gradlew check
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/local_test_caseworker_db
          SPRING_DATASOURCE_USERNAME: test_dev_user
          SPRING_DATASOURCE_PASSWORD: test_dev_password
          SPRING_PROFILES_ACTIVE: test

      # Frontend tests
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './Client/package-lock.json'
      
      - name: Install Frontend Dependencies
        working-directory: ./Client
        run: npm ci
      
      - name: Run Frontend Tests
        working-directory: ./Client
        run: npm run test:headless
